// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: (() => {
      const uri = process.env["MONGODB_URI"];
      const db = process.env["MONGODB_DB"];
      if (!uri) return "";
      if (!db) return uri;
      const base = uri.endsWith("/") ? uri.slice(0, -1) : uri;
      return `${base}/${db}?authSource=admin`;
    })(),
  },
});
